### PR TITLE
Fix: Handle connection lost on blocked screens

### LINKED ISSUE #466: Offline mode blocks access to screens, but does nothing if connection lost while already on the screen
- [ ] Reproduce the behavior
- [ ] Fix the root cause
- [ ] Write tests

### PR DESCRIPTION
**Pull request by Tuaer**
## Context
Previously, users could remain in critical screens requiring an active internet connection if the connection was lost while on these screens.

## What changed
- Implemented automatic navigation back on connection loss in critical Tasks screens
- Implemented automatic navigation back on connection loss across critical Meeting screens

## Why it changed
- Prevents users from being trapped in screens that cannot function properly offline
- Improves app resilience by gracefully handling connectivity interruptions in key areas

## Potential future bugs
- None identified

## Potential future improvements
- Display a user-friendly offline warning or toast before navigating back

Description partially generated by Grok
Closes #466

### CODE REVIEW

File: app/src/main/java/ch/eureka/eurekapp/screens/subscreens/meetings/MeetingAudioRecordingScreen.kt [hunk 1]
```diff
@@ -87,6 +88,12 @@ fun MeetingAudioRecordingScreen(
     onBackClick: () -> Unit = {}
 ) {
 
+  val connectivityObserver = ConnectivityObserverProvider.connectivityObserver
```
Comment (IliasSokolisGD) [inline app/src/main/java/ch/eureka/eurekapp/screens/subscreens/meetings/MeetingAudioRecordingScreen.kt]: Shouldn't the connectivity observer be in the audioRecordingViewModel as we usually do?

**Comment by Tuaer** [comment]
You're right about a missing user feedback. I will add a Toast.
